# Generated by Django 2.2 on 2019-10-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uf',
            name='fecha',
            field=models.CharField(max_length=24, primary_key=True, serialize=False),
        ),
    ]
