# Generated by Django 2.2 on 2019-10-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipc',
            name='fecha',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uf',
            name='fecha',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
